.gitignore
api/build.gradle.kts
api/src/migrationTest/kotlin/Migration.kt
api/src/migrationTest/kotlin/MigrationConfig.kt
api/src/migrationTest/kotlin/handler/TimeTableMigrations.kt
api/src/migrationTest/resources/application-migration.yaml

- unbroken-dome.test-sets 적용
- migrationTest 생성
- api 별로 이관하기 전에 migrationTest에다가 테스트 코드를 먼저 작성하고,migrationTest가 성공시키는 식으로 개발해나갔으면 함.

feat: migration test base

---

api/src/main/kotlin/com/wafflestudio/snu4t/handler/ServiceHandler.kt
api/src/main/kotlin/com/wafflestudio/snu4t/handler/TimeTableHandler.kt
api/src/main/kotlin/com/wafflestudio/snu4t/middleware/Middleware.kt

```
suspend fun getTimeTables(req: ServerRequest): ServerResponse = handle(req) {
val context = req.getContext()
val user = context.user ?: throw AuthException\
timeTableService.getTimeTablesOfUser(user)
}
```
마지막에 toResponse가 들어가는 게 이상해서 자동으로 리턴값을 ServerResponse로 변환하도록 변경
null 반환하면 noContent 응답해야할지 살짝 고민했는데 기존 서버 응답 어떻게 돼있는지 확인해봐야 할 듯

Update handle function to make ServerResponse

---

batch/src/main/kotlin/sugangsnu/SugangSnuSyncJobConfig.kt
batch/src/main/kotlin/sugangsnu/service/SugangSnuSyncService.kt
build.gradle.kts
core/src/main/kotlin/common/CacheRepository.kt
core/src/main/resources/application-common.yml

검색 시 캐시사용,
강의 업데이트 후 캐시로 인해 검색 데이터가 최신화 안될 가능성 있어 flushdb 사용

배치 완료 후 캐시 삭제

---

batch/src/main/kotlin/sugangsnu/SugangSnuRepository.kt
batch/src/main/kotlin/sugangsnu/service/SugangSnuFetchService.kt
batch/src/main/kotlin/sugangsnu/service/SugangSnuSyncService.kt

그냥 runCatching getOrDefault scope만 엑셀 변환쪽으로 변경

수강스누 장애 에러 핸들링

---

batch/src/main/kotlin/sugangsnu/service/SugangSnuNotificationService.kt

삭제된 강의 알림 Notification 타입 변경

---

api/src/main/kotlin/router/docs/AuthDocs.kt
api/src/main/kotlin/router/docs/BookmarkDocs.kt
api/src/main/kotlin/router/docs/SharedTimetableDocs.kt
api/src/main/kotlin/router/docs/TableDocs.kt
core/src/main/kotlin/config/SwaggerConfig.kt

swagger improvement : 헤더 주입해서 Try It Out 가능하도록 수정

---

api/src/main/kotlin/handler/BookmarkHandler.kt
api/src/main/kotlin/handler/NotificationHandler.kt
api/src/main/kotlin/handler/ServiceHandler.kt
api/src/main/kotlin/router/MainRouter.kt
api/src/main/kotlin/router/docs/NotificationApi.kt
core/src/main/kotlin/notification/dto/NotificationQuery.kt
core/src/main/kotlin/notification/repository/NotificationRepository.kt
core/src/main/kotlin/notification/service/NotificationService.kt
core/src/main/kotlin/users/service/UserService.kt

슥삭 해봤는데 놓친게 있는지 한 번 더 보긴 할게용
스웨거 앞에 꺼 선머지 되면 rebase merge 하겠슴다.

알림 API 2개 마이그레이션 

---

core/src/main/kotlin/sharedtimetable/data/SharedTimetable.kt
core/src/main/kotlin/sharedtimetable/dto/SharedTimetableDetailDto.kt
core/src/main/kotlin/sharedtimetable/dto/SharedTimetableListDto.kt
core/src/main/kotlin/sharedtimetable/service/SharedTimeTableService.kt
core/src/main/kotlin/timetables/data/Timetable.kt

- #22, #37 의 후속작업입니다. 
- Timetable의  json field 이름 변경 [[참고](https://wafflestudio.slack.com/archives/C0PAVPS5T/p1680105248433999)]
- SharedTimetable에 year, semester를 추가 [[참고](https://wafflestudio.slack.com/archives/C0PAVPS5T/p1680007980526219)]

공유시간표 기능 팔로업 

---

core/src/main/kotlin/users/repository/UserRepository.kt
core/src/main/kotlin/users/service/UserService.kt

https://wafflestudio.slack.com/archives/C052DL4F3C0/p1681306962967299
ㅇㅇ

유저 조회 시 탈퇴계정 제외

---

core/src/main/kotlin/common/enum/TimetableTheme.kt
core/src/main/kotlin/config/MongoDbConfig.kt
core/src/main/kotlin/timetables/data/Timetable.kt
core/src/main/kotlin/timetables/service/TimetableService.kt
core/src/main/kotlin/users/service/UserService.kt
core/src/test/kotlin/TestApplication.kt

기존 snutt 에 있던 로직인데 누락되어있어서 추가.

Create Default Timetable when Registering

---

api/src/main/kotlin/handler/AuthHandler.kt
api/src/main/kotlin/router/MainRouter.kt
api/src/main/kotlin/router/docs/AuthDocs.kt
core/src/main/kotlin/common/enum/TimetableTheme.kt
core/src/main/kotlin/common/exception/ErrorType.kt
core/src/main/kotlin/common/exception/Snu4tException.kt
core/src/main/kotlin/config/MongoDbConfig.kt
core/src/main/kotlin/timetables/data/Timetable.kt
core/src/main/kotlin/timetables/service/TimetableService.kt
core/src/main/kotlin/users/dto/LocalLoginRequest.kt
core/src/main/kotlin/users/dto/LoginResponse.kt
core/src/main/kotlin/users/repository/UserRepository.kt
core/src/main/kotlin/users/service/UserService.kt
core/src/test/kotlin/TestApplication.kt

https://github.com/wafflestudio/snutt-timetable/pull/62 의 다른 것이 배포되면 안 되어서
Cherry-pick https://github.com/wafflestudio/snutt-timetable/pull/60, https://github.com/wafflestudio/snutt-timetable/pull/61

Cherry-pick #60, #61

---

api/src/main/kotlin/handler/VacancyNotifcationHandler.kt
api/src/main/kotlin/router/MainRouter.kt
api/src/main/kotlin/router/docs/VacancyNotificationDocs.kt
batch/src/main/kotlin/sugangsnu/common/SugangSnuRepository.kt
batch/src/main/kotlin/sugangsnu/job/seat/data/AvailableSeatsNotificationResult.kt
batch/src/main/kotlin/sugangsnu/job/vacancynotification/VacancyNotificationJobConfig.kt
batch/src/main/kotlin/sugangsnu/job/vacancynotification/data/RegistrationStatus.kt
batch/src/main/kotlin/sugangsnu/job/vacancynotification/data/VacancyNotificationJobResult.kt
batch/src/main/kotlin/sugangsnu/job/vacancynotification/service/VacancyNotificationJobService.kt
core/src/main/kotlin/common/exception/ErrorType.kt
core/src/main/kotlin/common/exception/Snu4tException.kt
core/src/main/kotlin/lectures/repository/LectureCustomRepository.kt
core/src/main/kotlin/seatnotification/repository/SeatNotificationRepository.kt
core/src/main/kotlin/vacancynotification/data/VacancyNotification.kt
core/src/main/kotlin/vacancynotification/dto/VacancyNotificationDto.kt
core/src/main/kotlin/vacancynotification/repository/VacancyNotificationRepository.kt
core/src/main/kotlin/vacancynotification/service/VacancyNotificationService.kt

- seatNotification -> vacancyNotification 이름 변경
- 추가, 삭제 api 작성

[#72] 빈자리 알림 등록, 삭제 api 추가

---

api/src/main/kotlin/handler/NotificationHandler.kt
api/src/main/kotlin/router/MainRouter.kt
core/src/main/kotlin/notification/repository/NotificationRepository.kt
core/src/main/kotlin/notification/service/NotificationService.kt

1:11, 1:13, 1:14 시간에 맞춰서 보낸건데 순서 뒤죽박죽인거 fix

알림 최신순 정렬 추가

---

api/src/main/kotlin/handler/NotificationHandler.kt
core/src/main/kotlin/common/MongoExtensions.kt
core/src/main/kotlin/notification/dto/NotificationQuery.kt
core/src/main/kotlin/notification/repository/NotificationCustomRepository.kt
core/src/main/kotlin/notification/repository/NotificationRepository.kt
core/src/main/kotlin/notification/service/NotificationService.kt

@Jhvictor4 ㅠㅠ
페이지로 하는 쿼리가 아니라서 직접 쿼리짬ㅠ
물론 page로 잘 할 수 있겠지만 혹시 몰라서 limit, offset에 맞게 다시 짬
```java
// 분명 page request인데
PageRequest of(int page, int size)
// offset limit로 페이지 만듦
PageRequest.of(query.offset, query.limit)
```

알림 조회 조건 오류 수정

---

core/src/main/kotlin/lectures/dto/BookmarkLectureDto.kt
core/src/main/kotlin/lectures/dto/LectureDto.kt
core/src/main/kotlin/timetables/dto/TimetableLectureDto.kt

https://wafflestudio.slack.com/archives/C0PAVPS5T/p1687701324569889

classTimeMask response에서 빈 값 주도록 롤백

---

api/src/main/kotlin/router/MainRouter.kt
api/src/main/kotlin/router/docs/AdminDocs.kt
api/src/main/kotlin/router/docs/AuthDocs.kt
api/src/main/kotlin/router/docs/DeviceDocs.kt
api/src/main/kotlin/router/docs/NotificationDocs.kt

`@~Api` 와 `@~Docs` 혼용되던 것 `@~Docs`로 통일
누락된 Swagger docs 추가

Cleaning swagger docs & Add `DeviceDocs`

---

api/src/main/kotlin/router/MainRouter.kt

만드려다보니 이미 ping 이 있어서, 그냥 snutt-ev-web 이 만든 endpoint naming 따라서 패턴만 맞춤
liveness probe, readiness probe 용

health-check

---

api/src/main/kotlin/router/MainRouter.kt
api/src/main/kotlin/router/docs/UserDocs.kt

지금 보니 기존 snutt 랑 비교했을 때, route path 를 잘못 잡아서 수정. handler 는 구분해서 구현하려고 그냥 둠.

deviceRoute -> userRoute

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml

Fix typo in #113

---

batch/src/main/kotlin/sugangsnu/common/service/SugangSnuNotificationService.kt

Add space to noti title

---

core/src/main/kotlin/common/push/fcm/FcmPushClient.kt

Fix #118 
async { } 는 내부 exception 발생 시, 바로 이를 전파시키지 않고, Deferred 가 await() 될 때 전파시킴.
때문에, coroutine 이 종료되자마자 실행되는 `CoroutineExceptionHandler` 가 영향을 주지 못함.
그리고, `awaitAll()`할 때 coroutine 중 하나라도 exception 있었으면 부모 coroutine 도 터지면서 더 위로 전파될 수 있음.
https://kotlinlang.org/docs/exception-handling.html#coroutineexceptionhandler

Remove `CoroutineExceptionHandler` used with `async`

---

batch/src/main/kotlin/sugangsnu/job/sync/service/SugangSnuSyncService.kt

https://wafflestudio.slack.com/archives/C8M9NUBBR/p1689646538624089

겹강 삭제 버그 픽스

---

core/src/main/kotlin/lectures/repository/LectureCustomRepository.kt

https://github.com/wafflestudio/snutt-timetable/pull/93#discussion_r1266950012

제외 시간대 버그 픽스

---

core/src/main/kotlin/common/cache/Cache.kt

https://github.com/wafflestudio/snutt-timetable/pull/127#discussion_r1272272603 리뷰 반영.

#127 Cache 관련 리뷰 반영

---

batch/src/main/kotlin/sugangsnu/common/service/SugangSnuNotificationService.kt

https://wafflestudio.slack.com/archives/C8M9NUBBR/p1690556204698889?thread_ts=1690507957.653489&cid=C8M9NUBBR
푸시를 통해 유저가 알림함에서 더 자세한 정보를 볼 수 있단 점 알게 하기

modify push content sugang sync

---

api/src/main/kotlin/handler/FriendTableHandler.kt
api/src/main/kotlin/handler/TimetableHandler.kt
api/src/main/kotlin/router/MainRouter.kt
api/src/main/kotlin/router/docs/FriendDocs.kt
api/src/main/kotlin/router/docs/TableDocs.kt
core/src/main/kotlin/friend/data/Friend.kt
core/src/main/kotlin/friend/service/FriendService.kt
core/src/main/kotlin/timetables/data/SemesterDto.kt
core/src/main/kotlin/timetables/data/Timetable.kt
core/src/main/kotlin/timetables/dto/TimetableBriefDto.kt
core/src/main/kotlin/timetables/dto/TimetableDto.kt
core/src/main/kotlin/timetables/repository/TimetableCustomRepository.kt
core/src/main/kotlin/timetables/repository/TimetableRepository.kt
core/src/main/kotlin/timetables/service/TimetableService.kt

대표 시간표 지정 기능 및 친구의 대표 시간표 조회 기능

---

api/src/main/kotlin/router/docs/FriendDocs.kt
api/src/main/kotlin/router/docs/TableDocs.kt

Fix swagger bug related friends

---

api/src/main/kotlin/handler/UserHandler.kt
api/src/main/kotlin/router/MainRouter.kt
api/src/main/kotlin/router/docs/UserDocs.kt
core/src/main/kotlin/common/exception/ErrorType.kt
core/src/main/kotlin/common/exception/Snu4tException.kt
core/src/main/kotlin/users/data/User.kt
core/src/main/kotlin/users/dto/UserDto.kt
core/src/main/kotlin/users/dto/UserPatchRequest.kt
core/src/main/kotlin/users/service/UserNicknameService.kt
core/src/main/kotlin/users/service/UserService.kt

응답
```
{
"isAdmin": true,
"regDate": "2017-12-29T15:50:35.278",
"notificationCheckedAt": "2023-08-02T15:47:07.981",
"email": "bdv111@snu.ac.kr",
"localId": null,
"fbName": "변다빈",
"nickname": {
"nickname": "가가가가가가가가가가",
"tag": "5682"
}
}
```
요청 - 현재 nickname 만 받음
응답 (GET 과 동일)
```
{
"isAdmin": true,
"regDate": "2017-12-29T15:50:35.278",
"notificationCheckedAt": "2023-08-02T15:47:07.981",
"email": "bdv111@snu.ac.kr",
"localId": null,
"fbName": "변다빈",
"nickname": {
"nickname": "가가가가가가가가가가",
"tag": "5682"
}
}
```

get, patch users me

---

api/src/main/kotlin/handler/BookmarkHandler.kt
api/src/main/kotlin/handler/VacancyNotifcationHandler.kt
api/src/main/kotlin/router/MainRouter.kt
api/src/main/kotlin/router/docs/BookmarkDocs.kt
api/src/main/kotlin/router/docs/VacancyNotificationDocs.kt
core/src/main/kotlin/bookmark/service/BookmarkService.kt
core/src/main/kotlin/common/dto/ExistenceResponse.kt
core/src/main/kotlin/vacancynotification/repository/VacancyNotificationRepository.kt
core/src/main/kotlin/vacancynotification/service/VacancyNotificationService.kt

https://wafflestudio.slack.com/archives/C0PAVPS5T/p1691661911780579?thread_ts=1691660251.656059&cid=C0PAVPS5T

존재 확인 api 추가

---

batch/src/main/kotlin/sugangsnu/job/vacancynotification/service/VacancyNotifierService.kt

대신 부하 분산을 위해
전체과목을 1/20으로 나눠서 
요청 -> 해당 과목들만 업데이트/노티 반복

빈자리 알림 delay 제거

---

api/src/main/kotlin/handler/FriendTableHandler.kt
api/src/main/kotlin/router/MainRouter.kt
api/src/main/kotlin/router/docs/FriendDocs.kt
core/src/main/kotlin/timetables/service/TimetableService.kt

일관된 이름 사용
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1691562584073919?thread_ts=1691206392.965919&cid=C0PAVPS5T

courseBook -> coursebook

---

api/src/main/kotlin/handler/DeviceHandler.kt
api/src/main/kotlin/handler/FriendHandler.kt
api/src/main/kotlin/handler/UserHandler.kt
core/src/main/kotlin/friend/service/FriendService.kt
core/src/main/kotlin/users/data/User.kt
core/src/main/kotlin/users/service/UserService.kt

https://www.notion.so/wafflestudio/8ecf29305d044fa68f1ab6cca1e18263?pvs=4

friend push

---

core/src/main/kotlin/users/data/UserEntityCallback.kt
core/src/main/kotlin/users/service/UserNicknameBackFillSupporter.kt

Read 하는 모든 경우에 대해 닉네임 null인 경우 무조건 backfill

닉네임 Backfill 고도화

---

core/src/main/kotlin/common/exception/ErrorType.kt
core/src/main/kotlin/common/exception/Snu4tException.kt
core/src/main/kotlin/common/push/UrlScheme.kt
core/src/main/kotlin/friend/service/FriendService.kt

https://wafflestudio.slack.com/archives/C0PAVPS5T/p1694314969115449?thread_ts=1694309396.205729&cid=C0PAVPS5T

Resolve Friend QA Issues

---

batch/src/main/kotlin/sugangsnu/job/vacancynotification/service/VacancyNotifierService.kt
core/src/main/kotlin/notification/data/NotificationType.kt

알림 타입 추가 - 빈자리, 신규 피처

---

core/src/main/kotlin/lectures/repository/LectureCustomRepository.kt

`3-302`를 넣으면, 3-202, 3-202-xxx, 3-202-xxx(무선랜제공) 에 해당하는 거 다 검색됨.
기존처럼 띄어쓰기 기준으로 나눠져서, 다른 조건들과 and 로 조합됨.
7-302 -> 7동 302호 강의, 또는 만악 7동 302-x호 같은 거 있으면 그것도 포함
7-302-3 -> 7동 302-3호 강의
7동 -> 7동에서 열리는 강의가 뜸
대학영어 2동 -> ‘대학영어’라는 기존 검색 결과에 and 로 2동이란 조건이 붙음
대학영어 2 -> 기존 동작과 다를 바 없음

강의 place 검색 지원

---

core/src/main/kotlin/common/exception/ErrorType.kt
core/src/main/kotlin/common/exception/Snu4tException.kt
core/src/main/kotlin/timetables/service/TimetableService.kt

https://wafflestudio.slack.com/archives/C8M9NUBBR/p1704516184034529

title 빈칸으로 못만들도록 체크

---

core/src/main/kotlin/lectures/dto/ClassPlaceAndTimeDto.kt

- #216 요거에서 데이터 넣는 부분만 체리픽해서 우선 dev에 붓습니다

목데이터 대신 실제 데이터가 들어가도록 작업

---

core/src/main/kotlin/timetables/dto/TimetableThemeDto.kt
core/src/main/kotlin/timetables/service/TimetableThemeService.kt

https://wafflestudio.slack.com/archives/C0PAVPS5T/p1706525730511699

커스텀 테마가 하나도 없을 때, SNUTT 를 default 로 표시해주기

---

core/src/main/kotlin/timetables/service/TimetableThemeService.kt

https://wafflestudio.slack.com/archives/C052DL4F3C0/p1708658359318089 원인 파악을 위해 로그 남김

커스텀 테마 에러 케이스 관련 로깅

---

core/src/main/kotlin/timetables/service/TimetableThemeService.kt

https://wafflestudio.slack.com/archives/C052DL4F3C0/p1708756909079899

커스텀 테마 색상 수 줄이는 경우 버그 수정

---

core/src/main/kotlin/timetables/repository/TimetableThemeRepository.kt
core/src/main/kotlin/timetables/service/TimetableThemeService.kt

https://wafflestudio.slack.com/archives/C0PAVPS5T/p1709356971049649?thread_ts=1709130614.032699&cid=C0PAVPS5T

default theme 개념 제거

---

core/src/main/kotlin/timetables/data/TimetableTheme.kt
core/src/main/kotlin/timetables/repository/TimetableThemeRepository.kt
core/src/main/kotlin/timetables/service/TimetableThemeService.kt

default theme 관련 코드 정리

---

api/src/main/kotlin/handler/UserHandler.kt
api/src/main/kotlin/router/MainRouter.kt
api/src/main/kotlin/router/docs/UserDocs.kt

snutt-core에서와 같이 db에서 사용자의 active 플래그만 false로 바꾸게 만들었고 테스트도 해보았습니다.
리뷰 부탁드려요

회원 탈퇴 API 마이그레이션

---

api/src/main/kotlin/router/docs/FriendDocs.kt
api/src/main/kotlin/router/docs/UserDocs.kt

저번에 친구 링크 작업한게 friend 쪽 api인데 명세를 userdocs에 넣어버려서 옮겨야 할거 같아요
friend -> friends로 주소 수정도 같이 했어요

친구추가 링크 관련 FriendDocs로 이동

---

api/src/main/kotlin/handler/UserHandler.kt
api/src/main/kotlin/router/docs/UserDocs.kt
core/src/main/kotlin/users/dto/TokenResponse.kt
core/src/main/kotlin/users/service/UserService.kt

이메일 마이그레이션 했던거 반환값이 달라서 오류가 나는거 수정했습니다

TokenResponse를 attachLocal에서도 반환

---

api/src/main/kotlin/handler/LectureSearchHandler.kt
batch/src/main/kotlin/sugangsnu/job/sync/service/SugangSnuSyncService.kt
core/src/main/kotlin/common/enum/SortCriteria.kt
core/src/main/kotlin/lectures/data/EvInfo.kt
core/src/main/kotlin/lectures/data/Lecture.kt
core/src/main/kotlin/lectures/dto/SearchDto.kt
core/src/main/kotlin/lectures/repository/LectureCustomRepository.kt
core/src/main/kotlin/tag/data/TagList.kt

lecture에 evInfo라는 class를 필드로 추가해서 ev의 lecture id, avgRating, count를 저장하도록 했고 검색 쿼리에 sortCriteria:"RATING"을 넣으면 평점 순으로 정렬되게 했습니다.
ev에는 전체 동기화 배치와 강의평 변경 시 업데이트 기능도 pr로 올려두겠습니다
평점 저장하는 김에 ev lecture id도 같이 넣어두면 검색할때 ev로 요청 안넣어도 될거 같아서 넣어놨는데 어떨지 리뷰 부탁드립니다

검색에 평점순 정렬 추가

---

api/src/main/kotlin/router/docs/TagDocs.kt

tagdocs에 빠진게 있어서 swagger에 안떴었는데 수정했습니다
문서만 바뀌는거라 바로 머지하겠습니다

tags swagger 안뜨던거 수정

---

core/src/main/kotlin/users/service/UserService.kt

oauth2UserResponse에서 email이 null인 경우가 있어서 허용하게 처리했습니다

소셜 연동할때 email null인거 허용

---

core/src/main/kotlin/common/util/SugangSnuUrlUtils.kt

https://wafflestudio.slack.com/archives/C0PAVPS5T/p1729506123282199?thread_ts=1728361353.404059&cid=C0PAVPS5T
해당 방법 적용했습니다

도서관 학외접속 프록시로 강의계획서 접속 우회
